version: '3.8'

networks:
  cassandra-cinema:


services:
  cassandra-cinema-1:
    image: cassandra:latest
    container_name: cassandra-cinema-1
    hostname: cassandra-cinema-1
    networks:
      - cassandra-cinema
    ports:
      - "9042:9042"
    environment: &cassandra_environment
      CASSANDRA_SEEDS: "cassandra-cinema-1,cassandra-cinema-2"
      CASSANDRA_CLUSTER_NAME: CinemaCluster
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RACK1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128

  cassandra-cinema-2:
    image: cassandra:latest
    container_name: cassandra-cinema-2
    hostname: cassandra-cinema-2
    networks:
      - cassandra-cinema
    ports:
      - "9043:9042"
    environment: *cassandra_environment
    depends_on:
      - cassandra-cinema-1

  cassandra-cinema-3:
    image: cassandra:latest
    container_name: cassandra-cinema-3
    hostname: cassandra-cinema-3
    networks:
      - cassandra-cinema
    ports:
      - "9044:9042"
    environment: *cassandra_environment
    depends_on:
      - cassandra-cinema-2
